//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Quan_li_nha_hang_MVC.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ChuNhaHang
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ChuNhaHang()
        {
            this.tblTaiKhoan = new HashSet<tblTaiKhoan>();
        }
    
        public int ID_Assitant { get; set; }
        public string TenCH { get; set; }
        public string TenQL { get; set; }
        public string SDT { get; set; }
        public string Email { get; set; }
        public string PassWrord { get; set; }
        public Nullable<int> Id_NV { get; set; }

        public ChuNhaHang(int iD_Assitant, string tenCH, string tenQL, string sDT, string email, string passWrord, int? id_NV)
        {
            ID_Assitant = iD_Assitant;
            TenCH = tenCH;
            TenQL = tenQL;
            SDT = sDT;
            Email = email;
            PassWrord = passWrord;
            Id_NV = id_NV;
        }

        public virtual tblNhanVien tblNhanVien { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblTaiKhoan> tblTaiKhoan { get; set; }
    }
}
