//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Quan_li_nha_hang_MVC.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DanhSachNhanVien
    {
        public int ID_NhanVien { get; set; }
        public string TenNV { get; set; }
        public string NgaySinh { get; set; }
        public int GioiTinh { get; set; }
        public string IDCanCuoc { get; set; }
        public string SoDT { get; set; }
        public string TinhTrangSK { get; set; }
        public string NgayVaoLam { get; set; }
        public string TenChucVu { get; set; }
        public int LamViec { get; set; }
        public string QueQuan { get; set; }
    }
}
