//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Quan_li_nha_hang_MVC.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DanhSachHDCTT
    {
        public int ID_GiaoDich { get; set; }
        public int ID_HDOder { get; set; }
        public string TenKH { get; set; }
        public string GioVao { get; set; }
        public double TienBanDau { get; set; }
        public int TTThanhToan { get; set; }
    }
}
