//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Quan_li_nha_hang_MVC.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DanhSachGiaoDich
    {
        public int ID_GiaoDich { get; set; }
        public string TenGD { get; set; }
        public string ThoiGianGD { get; set; }
        public Nullable<int> ID_HD_Oder { get; set; }
        public string DO { get; set; }
        public string MO { get; set; }
        public int TinhTrang { get; set; }
        public string HinhThucTT { get; set; }
        public double PhiDV { get; set; }
        public double TienBanDau { get; set; }
        public double TienCuoi { get; set; }
        public string GhiChu { get; set; }
    }
}
