//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Quan_li_nha_hang_MVC.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DanhSachHoaDon
    {
        public string SoHieuHD { get; set; }
        public string NgayDat { get; set; }
        public string NgayGiao { get; set; }
        public double ThanhTien { get; set; }
        public string TenNV { get; set; }
        public string TenChucVu { get; set; }
        public int DuyetHD { get; set; }
    }
}
