//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Quan_li_nha_hang_MVC.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class DoAnQuanLiNHEntities : DbContext
    {
        public DoAnQuanLiNHEntities()
            : base("name=DoAnQuanLiNHEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<ChuNhaHang> ChuNhaHang { get; set; }
        public virtual DbSet<sysdiagrams> sysdiagrams { get; set; }
        public virtual DbSet<tblBanNH> tblBanNH { get; set; }
        public virtual DbSet<tblBuffet> tblBuffet { get; set; }
        public virtual DbSet<tblChiTietBuffet> tblChiTietBuffet { get; set; }
        public virtual DbSet<tblChiTietGoiMon> tblChiTietGoiMon { get; set; }
        public virtual DbSet<tblChiTietMon> tblChiTietMon { get; set; }
        public virtual DbSet<tblChiTietOderBuffet> tblChiTietOderBuffet { get; set; }
        public virtual DbSet<tblChucVu> tblChucVu { get; set; }
        public virtual DbSet<tblDatBan> tblDatBan { get; set; }
        public virtual DbSet<tblGiaoDich> tblGiaoDich { get; set; }
        public virtual DbSet<tblHDNhapHang> tblHDNhapHang { get; set; }
        public virtual DbSet<tblHDOder> tblHDOder { get; set; }
        public virtual DbSet<tblLoaiBan> tblLoaiBan { get; set; }
        public virtual DbSet<tblLoaiHang> tblLoaiHang { get; set; }
        public virtual DbSet<tblMatHang> tblMatHang { get; set; }
        public virtual DbSet<tblMonAn> tblMonAn { get; set; }
        public virtual DbSet<tblNhaCC> tblNhaCC { get; set; }
        public virtual DbSet<tblNhanVien> tblNhanVien { get; set; }
        public virtual DbSet<tblProductMix> tblProductMix { get; set; }
        public virtual DbSet<tblPhanQuyen> tblPhanQuyen { get; set; }
        public virtual DbSet<tblTaiKhoan> tblTaiKhoan { get; set; }
        public virtual DbSet<tblTonHang> tblTonHang { get; set; }
        public virtual DbSet<tblCT_ProductMix> tblCT_ProductMix { get; set; }
        public virtual DbSet<tblCTTonHang> tblCTTonHang { get; set; }
        public virtual DbSet<tblChiTietHDNH> tblChiTietHDNH { get; set; }
        public virtual DbSet<tblQuyenNV> tblQuyenNV { get; set; }
        public virtual DbSet<BanChoThanhToan> BanChoThanhToan { get; set; }
        public virtual DbSet<ChiTietHoaDonOder> ChiTietHoaDonOder { get; set; }
        public virtual DbSet<DanhSachGiaoDich> DanhSachGiaoDich { get; set; }
        public virtual DbSet<DanhSachHD> DanhSachHD { get; set; }
        public virtual DbSet<DanhSachHDCTT> DanhSachHDCTT { get; set; }
        public virtual DbSet<DanhSachHoaDon> DanhSachHoaDon { get; set; }
        public virtual DbSet<DanhSachMatHang> DanhSachMatHang { get; set; }
        public virtual DbSet<DanhSachNhanVien> DanhSachNhanVien { get; set; }
        public virtual DbSet<DatTruocBan> DatTruocBan { get; set; }
        public virtual DbSet<DSAllMatHang> DSAllMatHang { get; set; }
        public virtual DbSet<DsBanNH> DsBanNH { get; set; }
        public virtual DbSet<DsBuffet> DsBuffet { get; set; }
        public virtual DbSet<DsMonAnAll> DsMonAnAll { get; set; }
        public virtual DbSet<ThanhPhanHang> ThanhPhanHang { get; set; }
    
        public virtual ObjectResult<ChitietBanDat_Result> ChitietBanDat(Nullable<int> id)
        {
            var idParameter = id.HasValue ?
                new ObjectParameter("id", id) :
                new ObjectParameter("id", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<ChitietBanDat_Result>("ChitietBanDat", idParameter);
        }
    
        public virtual ObjectResult<ChiTietBuffet_Result> ChiTietBuffet(string mabf)
        {
            var mabfParameter = mabf != null ?
                new ObjectParameter("mabf", mabf) :
                new ObjectParameter("mabf", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<ChiTietBuffet_Result>("ChiTietBuffet", mabfParameter);
        }
    
        public virtual ObjectResult<ChiTietHoaDonGiMon_Result> ChiTietHoaDonGiMon(Nullable<int> mahd)
        {
            var mahdParameter = mahd.HasValue ?
                new ObjectParameter("mahd", mahd) :
                new ObjectParameter("mahd", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<ChiTietHoaDonGiMon_Result>("ChiTietHoaDonGiMon", mahdParameter);
        }
    
        public virtual ObjectResult<ChiTietNVTheoMa_Result> ChiTietNVTheoMa(Nullable<int> manv)
        {
            var manvParameter = manv.HasValue ?
                new ObjectParameter("manv", manv) :
                new ObjectParameter("manv", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<ChiTietNVTheoMa_Result>("ChiTietNVTheoMa", manvParameter);
        }
    
        public virtual ObjectResult<DannNhapAd_Result> DannNhapAd(string sodt, string pass)
        {
            var sodtParameter = sodt != null ?
                new ObjectParameter("sodt", sodt) :
                new ObjectParameter("sodt", typeof(string));
    
            var passParameter = pass != null ?
                new ObjectParameter("pass", pass) :
                new ObjectParameter("pass", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<DannNhapAd_Result>("DannNhapAd", sodtParameter, passParameter);
        }
    
        public virtual ObjectResult<Nullable<int>> DangKiNH(string tenCH, string soDT, string tenQL, string email, string pass)
        {
            var tenCHParameter = tenCH != null ?
                new ObjectParameter("TenCH", tenCH) :
                new ObjectParameter("TenCH", typeof(string));
    
            var soDTParameter = soDT != null ?
                new ObjectParameter("SoDT", soDT) :
                new ObjectParameter("SoDT", typeof(string));
    
            var tenQLParameter = tenQL != null ?
                new ObjectParameter("TenQL", tenQL) :
                new ObjectParameter("TenQL", typeof(string));
    
            var emailParameter = email != null ?
                new ObjectParameter("Email", email) :
                new ObjectParameter("Email", typeof(string));
    
            var passParameter = pass != null ?
                new ObjectParameter("Pass", pass) :
                new ObjectParameter("Pass", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Nullable<int>>("DangKiNH", tenCHParameter, soDTParameter, tenQLParameter, emailParameter, passParameter);
        }
    
        public virtual ObjectResult<DangNhapByUser_Result> DangNhapByUser(string sodt, string tendn, string pass)
        {
            var sodtParameter = sodt != null ?
                new ObjectParameter("sodt", sodt) :
                new ObjectParameter("sodt", typeof(string));
    
            var tendnParameter = tendn != null ?
                new ObjectParameter("tendn", tendn) :
                new ObjectParameter("tendn", typeof(string));
    
            var passParameter = pass != null ?
                new ObjectParameter("pass", pass) :
                new ObjectParameter("pass", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<DangNhapByUser_Result>("DangNhapByUser", sodtParameter, tendnParameter, passParameter);
        }
    
        public virtual ObjectResult<Nullable<int>> DangNhapNhanVien(string sodt, string tendn, string pass)
        {
            var sodtParameter = sodt != null ?
                new ObjectParameter("sodt", sodt) :
                new ObjectParameter("sodt", typeof(string));
    
            var tendnParameter = tendn != null ?
                new ObjectParameter("tendn", tendn) :
                new ObjectParameter("tendn", typeof(string));
    
            var passParameter = pass != null ?
                new ObjectParameter("pass", pass) :
                new ObjectParameter("pass", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Nullable<int>>("DangNhapNhanVien", sodtParameter, tendnParameter, passParameter);
        }
    
        public virtual ObjectResult<DanhSachTonHangTN_Result> DanhSachTonHangTN(string ngay)
        {
            var ngayParameter = ngay != null ?
                new ObjectParameter("ngay", ngay) :
                new ObjectParameter("ngay", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<DanhSachTonHangTN_Result>("DanhSachTonHangTN", ngayParameter);
        }
    
        public virtual int DatBan(string tenkh, string sodt, Nullable<System.DateTime> ngaydat, string giodat, Nullable<int> sokhach, string idban)
        {
            var tenkhParameter = tenkh != null ?
                new ObjectParameter("tenkh", tenkh) :
                new ObjectParameter("tenkh", typeof(string));
    
            var sodtParameter = sodt != null ?
                new ObjectParameter("sodt", sodt) :
                new ObjectParameter("sodt", typeof(string));
    
            var ngaydatParameter = ngaydat.HasValue ?
                new ObjectParameter("ngaydat", ngaydat) :
                new ObjectParameter("ngaydat", typeof(System.DateTime));
    
            var giodatParameter = giodat != null ?
                new ObjectParameter("giodat", giodat) :
                new ObjectParameter("giodat", typeof(string));
    
            var sokhachParameter = sokhach.HasValue ?
                new ObjectParameter("sokhach", sokhach) :
                new ObjectParameter("sokhach", typeof(int));
    
            var idbanParameter = idban != null ?
                new ObjectParameter("idban", idban) :
                new ObjectParameter("idban", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("DatBan", tenkhParameter, sodtParameter, ngaydatParameter, giodatParameter, sokhachParameter, idbanParameter);
        }
    
        public virtual ObjectResult<DetailViewBf_Result> DetailViewBf(string mabg)
        {
            var mabgParameter = mabg != null ?
                new ObjectParameter("mabg", mabg) :
                new ObjectParameter("mabg", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<DetailViewBf_Result>("DetailViewBf", mabgParameter);
        }
    
        public virtual int DoanhThuThangNay(string thang, string nam)
        {
            var thangParameter = thang != null ?
                new ObjectParameter("thang", thang) :
                new ObjectParameter("thang", typeof(string));
    
            var namParameter = nam != null ?
                new ObjectParameter("nam", nam) :
                new ObjectParameter("nam", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("DoanhThuThangNay", thangParameter, namParameter);
        }
    
        public virtual ObjectResult<DsHangTheoHD_Result> DsHangTheoHD(string mahd)
        {
            var mahdParameter = mahd != null ?
                new ObjectParameter("mahd", mahd) :
                new ObjectParameter("mahd", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<DsHangTheoHD_Result>("DsHangTheoHD", mahdParameter);
        }
    
        public virtual int DuyetHang(Nullable<double> soluong, string mahd, string mah)
        {
            var soluongParameter = soluong.HasValue ?
                new ObjectParameter("soluong", soluong) :
                new ObjectParameter("soluong", typeof(double));
    
            var mahdParameter = mahd != null ?
                new ObjectParameter("mahd", mahd) :
                new ObjectParameter("mahd", typeof(string));
    
            var mahParameter = mah != null ?
                new ObjectParameter("mah", mah) :
                new ObjectParameter("mah", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("DuyetHang", soluongParameter, mahdParameter, mahParameter);
        }
    
        public virtual ObjectResult<HoaDonTheoBan_Result> HoaDonTheoBan(string maban)
        {
            var mabanParameter = maban != null ?
                new ObjectParameter("maban", maban) :
                new ObjectParameter("maban", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<HoaDonTheoBan_Result>("HoaDonTheoBan", mabanParameter);
        }
    
        public virtual int HuyBanDat(Nullable<int> maban, string mabannh)
        {
            var mabanParameter = maban.HasValue ?
                new ObjectParameter("maban", maban) :
                new ObjectParameter("maban", typeof(int));
    
            var mabannhParameter = mabannh != null ?
                new ObjectParameter("mabannh", mabannh) :
                new ObjectParameter("mabannh", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("HuyBanDat", mabanParameter, mabannhParameter);
        }
    
        public virtual ObjectResult<Nullable<int>> MaMixTimKiem(string ngay, Nullable<int> manv, string note)
        {
            var ngayParameter = ngay != null ?
                new ObjectParameter("ngay", ngay) :
                new ObjectParameter("ngay", typeof(string));
    
            var manvParameter = manv.HasValue ?
                new ObjectParameter("manv", manv) :
                new ObjectParameter("manv", typeof(int));
    
            var noteParameter = note != null ?
                new ObjectParameter("note", note) :
                new ObjectParameter("note", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Nullable<int>>("MaMixTimKiem", ngayParameter, manvParameter, noteParameter);
        }
    
        public virtual ObjectResult<SoluongBuffetToDay_Result> SoluongBuffetToDay(string ngay)
        {
            var ngayParameter = ngay != null ?
                new ObjectParameter("ngay", ngay) :
                new ObjectParameter("ngay", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SoluongBuffetToDay_Result>("SoluongBuffetToDay", ngayParameter);
        }
    
        public virtual int sp_alterdiagram(string diagramname, Nullable<int> owner_id, Nullable<int> version, byte[] definition)
        {
            var diagramnameParameter = diagramname != null ?
                new ObjectParameter("diagramname", diagramname) :
                new ObjectParameter("diagramname", typeof(string));
    
            var owner_idParameter = owner_id.HasValue ?
                new ObjectParameter("owner_id", owner_id) :
                new ObjectParameter("owner_id", typeof(int));
    
            var versionParameter = version.HasValue ?
                new ObjectParameter("version", version) :
                new ObjectParameter("version", typeof(int));
    
            var definitionParameter = definition != null ?
                new ObjectParameter("definition", definition) :
                new ObjectParameter("definition", typeof(byte[]));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_alterdiagram", diagramnameParameter, owner_idParameter, versionParameter, definitionParameter);
        }
    
        public virtual int sp_creatediagram(string diagramname, Nullable<int> owner_id, Nullable<int> version, byte[] definition)
        {
            var diagramnameParameter = diagramname != null ?
                new ObjectParameter("diagramname", diagramname) :
                new ObjectParameter("diagramname", typeof(string));
    
            var owner_idParameter = owner_id.HasValue ?
                new ObjectParameter("owner_id", owner_id) :
                new ObjectParameter("owner_id", typeof(int));
    
            var versionParameter = version.HasValue ?
                new ObjectParameter("version", version) :
                new ObjectParameter("version", typeof(int));
    
            var definitionParameter = definition != null ?
                new ObjectParameter("definition", definition) :
                new ObjectParameter("definition", typeof(byte[]));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_creatediagram", diagramnameParameter, owner_idParameter, versionParameter, definitionParameter);
        }
    
        public virtual int sp_dropdiagram(string diagramname, Nullable<int> owner_id)
        {
            var diagramnameParameter = diagramname != null ?
                new ObjectParameter("diagramname", diagramname) :
                new ObjectParameter("diagramname", typeof(string));
    
            var owner_idParameter = owner_id.HasValue ?
                new ObjectParameter("owner_id", owner_id) :
                new ObjectParameter("owner_id", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_dropdiagram", diagramnameParameter, owner_idParameter);
        }
    
        public virtual ObjectResult<sp_helpdiagramdefinition_Result> sp_helpdiagramdefinition(string diagramname, Nullable<int> owner_id)
        {
            var diagramnameParameter = diagramname != null ?
                new ObjectParameter("diagramname", diagramname) :
                new ObjectParameter("diagramname", typeof(string));
    
            var owner_idParameter = owner_id.HasValue ?
                new ObjectParameter("owner_id", owner_id) :
                new ObjectParameter("owner_id", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_helpdiagramdefinition_Result>("sp_helpdiagramdefinition", diagramnameParameter, owner_idParameter);
        }
    
        public virtual ObjectResult<sp_helpdiagrams_Result> sp_helpdiagrams(string diagramname, Nullable<int> owner_id)
        {
            var diagramnameParameter = diagramname != null ?
                new ObjectParameter("diagramname", diagramname) :
                new ObjectParameter("diagramname", typeof(string));
    
            var owner_idParameter = owner_id.HasValue ?
                new ObjectParameter("owner_id", owner_id) :
                new ObjectParameter("owner_id", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_helpdiagrams_Result>("sp_helpdiagrams", diagramnameParameter, owner_idParameter);
        }
    
        public virtual int sp_renamediagram(string diagramname, Nullable<int> owner_id, string new_diagramname)
        {
            var diagramnameParameter = diagramname != null ?
                new ObjectParameter("diagramname", diagramname) :
                new ObjectParameter("diagramname", typeof(string));
    
            var owner_idParameter = owner_id.HasValue ?
                new ObjectParameter("owner_id", owner_id) :
                new ObjectParameter("owner_id", typeof(int));
    
            var new_diagramnameParameter = new_diagramname != null ?
                new ObjectParameter("new_diagramname", new_diagramname) :
                new ObjectParameter("new_diagramname", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_renamediagram", diagramnameParameter, owner_idParameter, new_diagramnameParameter);
        }
    
        public virtual int sp_upgraddiagrams()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_upgraddiagrams");
        }
    
        public virtual ObjectResult<Nullable<double>> TongHangDaGoiTheoNgay(string ngay, string mah)
        {
            var ngayParameter = ngay != null ?
                new ObjectParameter("ngay", ngay) :
                new ObjectParameter("ngay", typeof(string));
    
            var mahParameter = mah != null ?
                new ObjectParameter("mah", mah) :
                new ObjectParameter("mah", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Nullable<double>>("TongHangDaGoiTheoNgay", ngayParameter, mahParameter);
        }
    
        public virtual ObjectResult<Nullable<double>> TongTienSPTonKho(string ngay, string mah)
        {
            var ngayParameter = ngay != null ?
                new ObjectParameter("ngay", ngay) :
                new ObjectParameter("ngay", typeof(string));
    
            var mahParameter = mah != null ?
                new ObjectParameter("mah", mah) :
                new ObjectParameter("mah", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Nullable<double>>("TongTienSPTonKho", ngayParameter, mahParameter);
        }
    
        public virtual int ThemMonAnBF(Nullable<int> hdhd, string mamon, Nullable<double> soluong, string giooder)
        {
            var hdhdParameter = hdhd.HasValue ?
                new ObjectParameter("hdhd", hdhd) :
                new ObjectParameter("hdhd", typeof(int));
    
            var mamonParameter = mamon != null ?
                new ObjectParameter("mamon", mamon) :
                new ObjectParameter("mamon", typeof(string));
    
            var soluongParameter = soluong.HasValue ?
                new ObjectParameter("soluong", soluong) :
                new ObjectParameter("soluong", typeof(double));
    
            var giooderParameter = giooder != null ?
                new ObjectParameter("giooder", giooder) :
                new ObjectParameter("giooder", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("ThemMonAnBF", hdhdParameter, mamonParameter, soluongParameter, giooderParameter);
        }
    
        public virtual int ThemSuatBF(Nullable<int> hdhd, string mamon, Nullable<double> soluong, string giooder)
        {
            var hdhdParameter = hdhd.HasValue ?
                new ObjectParameter("hdhd", hdhd) :
                new ObjectParameter("hdhd", typeof(int));
    
            var mamonParameter = mamon != null ?
                new ObjectParameter("mamon", mamon) :
                new ObjectParameter("mamon", typeof(string));
    
            var soluongParameter = soluong.HasValue ?
                new ObjectParameter("soluong", soluong) :
                new ObjectParameter("soluong", typeof(double));
    
            var giooderParameter = giooder != null ?
                new ObjectParameter("giooder", giooder) :
                new ObjectParameter("giooder", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("ThemSuatBF", hdhdParameter, mamonParameter, soluongParameter, giooderParameter);
        }
    
        public virtual int UpDateAll(string mahd)
        {
            var mahdParameter = mahd != null ?
                new ObjectParameter("mahd", mahd) :
                new ObjectParameter("mahd", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("UpDateAll", mahdParameter);
        }
    
        public virtual ObjectResult<string> XoaHoaDonTheoMa(string mahd)
        {
            var mahdParameter = mahd != null ?
                new ObjectParameter("mahd", mahd) :
                new ObjectParameter("mahd", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<string>("XoaHoaDonTheoMa", mahdParameter);
        }
    }
}
