//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Quan_li_nha_hang_MVC.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DSAllMatHang
    {
        public string ID_Hang { get; set; }
        public string TenHang { get; set; }
        public string MoTa { get; set; }
        public double SoLuong { get; set; }
        public string DonViTon { get; set; }
        public double MucGia { get; set; }
        public string HanSudung { get; set; }
        public string TenLoai { get; set; }
        public string TenNCC { get; set; }
    }
}
