//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Quan_li_nha_hang_MVC.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DsBanNH
    {
        public string ID_Ban { get; set; }
        public string TenBan { get; set; }
        public string MoTa { get; set; }
        public string ViTri { get; set; }
        public int SoGhe { get; set; }
        public int TinhTrang { get; set; }
        public string KhuVuc { get; set; }
        public int SuDung { get; set; }
        public string TenLoaiBan { get; set; }
    }
}
