//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Quan_li_nha_hang_MVC.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DsMonAnAll
    {
        public string ID_MonAn { get; set; }
        public string TenMon { get; set; }
        public double GiaMon { get; set; }
        public string MoTa { get; set; }
        public string TracMon { get; set; }
        public Nullable<int> SuDung { get; set; }
        public string HinhAnh { get; set; }
    }
}
