//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Quan_li_nha_hang_MVC.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblBanNH
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tblBanNH()
        {
            this.tblDatBan = new HashSet<tblDatBan>();
            this.tblHDOder = new HashSet<tblHDOder>();
        }
    
        public string ID_Ban { get; set; }
        public string TenBan { get; set; }
        public string MoTa { get; set; }
        public string ViTri { get; set; }
        public int SoGhe { get; set; }
        public int TinhTrang { get; set; }
        public string KhuVuc { get; set; }
        public string ID_LoaiBan { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblDatBan> tblDatBan { get; set; }
        public virtual tblLoaiBan tblLoaiBan { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblHDOder> tblHDOder { get; set; }
    }
}
