//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Quan_li_nha_hang_MVC.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblBuffet
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tblBuffet()
        {
            this.tblChiTietOderBuffet = new HashSet<tblChiTietOderBuffet>();
            this.tblChiTietBuffet = new HashSet<tblChiTietBuffet>();
        }
    
        public string ID_Buffe { get; set; }
        public string TenBF { get; set; }
        public double GiaBF { get; set; }
        public string NgayTao { get; set; }
        public double Thue { get; set; }
        public int SuDung { get; set; }
        public string Image { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblChiTietOderBuffet> tblChiTietOderBuffet { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblChiTietBuffet> tblChiTietBuffet { get; set; }
    }
}
