//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Quan_li_nha_hang_MVC.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblChiTietGoiMon
    {
        public int ID_HDOder { get; set; }
        public string ID_Mon { get; set; }
        public int SoLuong { get; set; }
        public string GioOder { get; set; }
    
        public virtual tblMonAn tblMonAn { get; set; }
        public virtual tblHDOder tblHDOder { get; set; }
    }
}
