//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Quan_li_nha_hang_MVC.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblCTTonHang
    {
        public Nullable<int> ID_TonH { get; set; }
        public string Id_Hang { get; set; }
        public double SoLuong { get; set; }
        public string GhiChu { get; set; }
        public string KhuVuc { get; set; }
    
        public virtual tblMatHang tblMatHang { get; set; }
        public virtual tblTonHang tblTonHang { get; set; }
    }
}
