//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Quan_li_nha_hang_MVC.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblChiTietBuffet
    {
        public string ID_Buffet { get; set; }
        public string ID_Mon { get; set; }
        public double SoLuong { get; set; }
        public double TongTien { get; set; }
    
        public virtual tblBuffet tblBuffet { get; set; }
        public virtual tblMonAn tblMonAn { get; set; }
    }
}
