//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Quan_li_nha_hang_MVC.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblChiTietHDNH
    {
        public string ID_HDNH { get; set; }
        public string ID_Hang { get; set; }
        public double SoLuong { get; set; }
        public int DuyetH { get; set; }
    
        public virtual tblHDNhapHang tblHDNhapHang { get; set; }
        public virtual tblMatHang tblMatHang { get; set; }
    }
}
