//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Quan_li_nha_hang_MVC.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblCT_ProductMix
    {
        public Nullable<int> ID_Mix { get; set; }
        public string ID_Hang { get; set; }
        public string TenHang { get; set; }
        public string DonViTon { get; set; }
        public double GiaHang { get; set; }
        public double TonKho { get; set; }
        public double TonDau { get; set; }
        public double NhapThuc { get; set; }
        public double XuatThuc { get; set; }
        public double PhanTram { get; set; }
        public string TenLoai { get; set; }
        public string NhaCC { get; set; }
        public string SuaDoi { get; set; }
    
        public virtual tblMatHang tblMatHang { get; set; }
        public virtual tblProductMix tblProductMix { get; set; }
    }
}
