//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Quan_li_nha_hang_MVC.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblDatBan
    {
        public int ID_Ban { get; set; }
        public string TenKH { get; set; }
        public string SoDT { get; set; }
        public string NgayDat { get; set; }
        public string GioDat { get; set; }
        public int SoKhach { get; set; }
        public string ID_BanDat { get; set; }
        public string Note { get; set; }
        public int TinhTrang { get; set; }
        public int HuyBan { get; set; }
    
        public virtual tblBanNH tblBanNH { get; set; }
    }
}
