//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Quan_li_nha_hang_MVC.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblHDOder
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tblHDOder()
        {
            this.tblChiTietGoiMon = new HashSet<tblChiTietGoiMon>();
            this.tblChiTietOderBuffet = new HashSet<tblChiTietOderBuffet>();
            this.tblGiaoDich = new HashSet<tblGiaoDich>();
        }
    
        public int ID_HDOder { get; set; }
        public string TenKH { get; set; }
        public string SoDT { get; set; }
        public string NgayVao { get; set; }
        public string GioVao { get; set; }
        public string GioRa { get; set; }
        public int SoKhach { get; set; }
        public int ID_NV { get; set; }
        public string ID_Ban { get; set; }
        public double Thue { get; set; }
        public double TongTien { get; set; }
        public string GhiChu { get; set; }
        public int TTThanhToan { get; set; }
    
        public virtual tblBanNH tblBanNH { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblChiTietGoiMon> tblChiTietGoiMon { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblChiTietOderBuffet> tblChiTietOderBuffet { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblGiaoDich> tblGiaoDich { get; set; }
        public virtual tblNhanVien tblNhanVien { get; set; }
    }
}
