//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Quan_li_nha_hang_MVC.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblMatHang
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tblMatHang()
        {
            this.tblChiTietMon = new HashSet<tblChiTietMon>();
            this.tblCT_ProductMix = new HashSet<tblCT_ProductMix>();
            this.tblCTTonHang = new HashSet<tblCTTonHang>();
            this.tblChiTietHDNH = new HashSet<tblChiTietHDNH>();
        }
    
        public string ID_Hang { get; set; }
        public string TenHang { get; set; }
        public string MoTa { get; set; }
        public double SoLuong { get; set; }
        public string DonViTon { get; set; }
        public double MucGia { get; set; }
        public string HanSudung { get; set; }
        public string ID_LoaiH { get; set; }
        public string ID_NCC { get; set; }
        public Nullable<int> SuDung { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblChiTietMon> tblChiTietMon { get; set; }
        public virtual tblLoaiHang tblLoaiHang { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblCT_ProductMix> tblCT_ProductMix { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblCTTonHang> tblCTTonHang { get; set; }
        public virtual tblNhaCC tblNhaCC { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblChiTietHDNH> tblChiTietHDNH { get; set; }
    }
}
