//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Quan_li_nha_hang_MVC.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblNhanVien
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tblNhanVien()
        {
            this.ChuNhaHang = new HashSet<ChuNhaHang>();
            this.tblGiaoDich = new HashSet<tblGiaoDich>();
            this.tblGiaoDich1 = new HashSet<tblGiaoDich>();
            this.tblHDNhapHang = new HashSet<tblHDNhapHang>();
            this.tblHDOder = new HashSet<tblHDOder>();
            this.tblTaiKhoan = new HashSet<tblTaiKhoan>();
            this.tblQuyenNV = new HashSet<tblQuyenNV>();
            this.tblTonHang = new HashSet<tblTonHang>();
            this.tblProductMix = new HashSet<tblProductMix>();
        }
    
        public int ID_NhanVien { get; set; }
        public string TenNV { get; set; }
        public string NgaySinh { get; set; }
        public int GioiTinh { get; set; }
        public string IDCanCuoc { get; set; }
        public string SoDT { get; set; }
        public string TinhTrangSK { get; set; }
        public string NgayVaoLam { get; set; }
        public string ID_ChucVu { get; set; }
        public int LamViec { get; set; }
        public string QueQuan { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ChuNhaHang> ChuNhaHang { get; set; }
        public virtual tblChucVu tblChucVu { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblGiaoDich> tblGiaoDich { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblGiaoDich> tblGiaoDich1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblHDNhapHang> tblHDNhapHang { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblHDOder> tblHDOder { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblTaiKhoan> tblTaiKhoan { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblQuyenNV> tblQuyenNV { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblTonHang> tblTonHang { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblProductMix> tblProductMix { get; set; }
    }
}
