//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Quan_li_nha_hang_MVC.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblProductMix
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tblProductMix()
        {
            this.tblCT_ProductMix = new HashSet<tblCT_ProductMix>();
        }
    
        public int ID_Pr_Mix { get; set; }
        public string TenTon { get; set; }
        public string NgayTon { get; set; }
        public Nullable<int> IdNV { get; set; }
        public string GhiChu { get; set; }
    
        public virtual tblNhanVien tblNhanVien { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblCT_ProductMix> tblCT_ProductMix { get; set; }
    }
}
