//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Quan_li_nha_hang_MVC.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblQuyenNV
    {
        public int ID_NhanVien { get; set; }
        public string ID_PhanQuyen { get; set; }
        public string NgayPQ { get; set; }
    
        public virtual tblNhanVien tblNhanVien { get; set; }
        public virtual tblPhanQuyen tblPhanQuyen { get; set; }
    }
}
