//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Quan_li_nha_hang_MVC.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblTonHang
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tblTonHang()
        {
            this.tblCTTonHang = new HashSet<tblCTTonHang>();
        }
    
        public int ID_THang { get; set; }
        public string TenTonH { get; set; }
        public string NgayTon { get; set; }
        public string KhuVuc { get; set; }
        public int MaNV { get; set; }
        public string GhiChu { get; set; }
    
        public virtual tblNhanVien tblNhanVien { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblCTTonHang> tblCTTonHang { get; set; }
    }
}
