//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Quan_li_nha_hang_MVC.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblTaiKhoan
    {
        public int ID_Acc { get; set; }
        public Nullable<int> ID_NV { get; set; }
        public string TenDn { get; set; }
        public string Email { get; set; }
        public string SoDT { get; set; }
        public string PassWrord { get; set; }
        public int Type { get; set; }
        public Nullable<int> MaNH { get; set; }
    
        public virtual ChuNhaHang ChuNhaHang { get; set; }
        public virtual tblNhanVien tblNhanVien { get; set; }
    }
}
