//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Quan_li_nha_hang_MVC.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ThanhPhanHang
    {
        public string TenLoai { get; set; }
        public Nullable<int> SoLuong { get; set; }
    }
}
